version: "3"
services:
  app:
    container_name: golden-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - GOLDEN_DB_URL=db
      - GOLDEN_DB_PASSWORD=DevOps
      - GOLDEN_DB_USERNAME=root
      - GOLDEN_DB_NAME=goldenwaste
      - GOLDEN_DB_PORT=3306
    depends_on:
      - db

  db:
    image: "mysql"
    container_name: goldenwastesqldb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=goldenwaste
      - MYSQL_ROOT_PASSWORD=DevOps